"""Initial migration

Revision ID: 249229bfe1f9
Revises: 
Create Date: 2025-08-20 22:28:11.607793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249229bfe1f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('turno_actual', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_cambio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('turno_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Integer(), nullable=False),
    sa.Column('docente', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('accion', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('turno_historial')
    op.drop_table('mesas')
    # ### end Alembic commands ###
